spring:
  datasource:
    url: jdbc:mysql://47.242.21.112:3306/weather?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: weather
    password: 123456aA?
    driver-class-name: com.mysql.cj.jdbc.Driver


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    storage:
      minio:
        bucketName: develop
        endpoint: http://47.242.21.112:9000
        access-key: admin
        secret-key: 123456aA?
        urlPrefix: http://47.242.21.112:9000/
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  tomcat:
    max-swallow-size: 100MB



mybatis:
  #mapper配置文件地址
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxy.practiceproject.demo.pojo
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted_status # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

logging:
  level:
    com.zxy: DEBUG


zxy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: "r8z1ZQWJjwvPZ6qjgX0YQz8xPZ1JwvPZ6qjgX0YQz=="
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: authorization

    user-secret-key: "r8z1ZQWJjwvPZ6qjgX0YQz8xPZ1JwvPZ6qjgX0YQz=="

    user-ttl: 7200000

    user-token-name: authentication


file:
  urlPrefix: http://47.242.21.112:9000/